### ISSUE TITLE
http issue on GitHubPages

### ISSUE THREAD

**Issue by jeanbellynck** [jeanbellynck/Cayley-Graph-Generator#103]
Find out how to fix the server connectivity. 

https://stackoverflow.com/questions/56936389/make-http-request-from-github-pages-https-hosted-site

**Comment by jeanbellynck** [comment]
I think, this can't be changed on GitHubPages. 
We can't go away from GitHub-Pages since the domain has been already saved by our users (except if we redirect to a new link)
I guess, we need a https server?

**Comment by p4jo** [comment]
Fixed, we now have https on graphcayley.de :D
