### ISSUE TITLE
Redirect processing more toward the internal 'word problems', less towards drawing the graph

### ISSUE THREAD

**Issue by p4jo** [jeanbellynck/Cayley-Graph-Generator#16]
**Reduce spasms of the graph and potentially increase performance**
The graph seems to be redrawn several times per second, which on my devices looks like it's doubled since it mostly jumps around wildly between two configurations.
I propose to redraw (update) it less frequently, instead focusing a bit more power onto generating ahead new potential elements to also decrease the number of times where a vertex is shown that is actually the same group element as another vertex, thus will be collapsed into the existing graph.

**Comment by p4jo** [comment]
The spasms have been fixed.
But with groups coming from the random graph group functionality the first seconds of the creation are still very violent. We might profit from simulating new nodes without showing them for a few seconds

**Comment by p4jo** [comment]
this also relates to #42

**Comment by jeanbellynck** [comment]
I also reduced the spasms by reducing the time step inverse proportionally to the generator count.

**Comment by jeanbellynck** [comment]
I remove this since we can reduce the presentations.
