### ISSUE TITLE
Additional rotation after pinch-to-zoom on ipados 

### ISSUE THREAD

**Issue by AndrewKepert** [jeanbellynck/Cayley-Graph-Generator#17]
Possible interface bug within Safari on iPadOS.
After graph is generated, zooming via pinch gesture causes orientation of graph to randomly change after zooming.  
The fixed node corresponding to the group identity stays fixed, but the nodes corresponding to the generators seem to adopt random values.
Possibly the pinch gesture is being treated firstly as a zoom, but then when it is released it is reinterpreted as a swipe gesture which causes a rotation in the model.  (Guessing here.)
Zooming via mouse scroll on ipadOS doesn't have this problem.  (I don't usually use a mouse here, but I can, so I did.)
Zooming via mouse scroll on similar platforms (macOS Safari and Chrome) also doesn't have this problem.

**Comment by jeanbellynck** [comment]
Thank you for creating the issue! I'll attempt to fix the issue the coming week.
