### ISSUE TITLE
Check whether we run relators backwards

### ISSUE THREAD

**Issue by jeanbellynck** [jeanbellynck/Cayley-Graph-Generator#54]
I think the code only checks for cycles by running relators forward but not by running them backwards. This might cause weird generation glitches

**Comment by p4jo** [comment]
Also, we should reduce all relators with the others to find a better relator set. I would like to have something like this:
https://docs.gap-system.org/doc/ref/chap47_mj.html#X7F28268F850F454E
Tietze moves etc

**Comment by jeanbellynck** [comment]
The issue has been implemented. Ill keep it open because I got to like the idea of reducing the relator set, as long as it does not make the graph look different.

**Comment by p4jo** [comment]
Now that GAP is implemented, we can actually use its methods to reduce presentations, also keeping the Gen set
