### ISSUE TITLE
Vertex label on hover

### ISSUE THREAD

**Issue by jeanbellynck** [jeanbellynck/Cayley-Graph-Generator#68]
Add label of a vertex on mouse hover. Different paths to the identity are already saved after all.
Idea from reddit: https://www.reddit.com/r/math/comments/1aimjq8/understanding_groups_and_drawing_pretty_pictures/

**Comment by p4jo** [comment]
Extra bonus: highlight all the paths to the identity (make the edges glow or like with a text marker, or just make them larger, or sparkle or change color as an animation etc)

**Comment by jeanbellynck** [comment]
A great idea! You might click on a vertex to highlight it and it's path to the identity. Then you might click again to make this vertex the new Center.

**Comment by p4jo** [comment]
The vertex label was implemented, and left-clicking makes it the center. We could still highlight the saved paths from the identity
