### ISSUE TITLE
Make all parallel line edges visible

### ISSUE THREAD

**Issue by p4jo** [jeanbellynck/Cayley-Graph-Generator#74]
When edges in the old style get drawn on top of each other, it is widely undefined which one is at the top, the other ones are invisible.

With splines, we also currently have this problem, edges are wildly switching color when rotating the view -> increase parallelEdgesFactor?

**Comment by p4jo** [comment]
![Screenshot_20240214_154529_Firefox](https://github.com/jeanbellynck/Cayley-Graph-Generator/assets/44933755/0008bf00-5222-48fa-a26a-2e3d0ea2b212)
![Screenshot_20240214_154729_Firefox](https://github.com/jeanbellynck/Cayley-Graph-Generator/assets/44933755/685c3324-85a3-4253-94ff-7c270d67a727)
![Screenshot_20240214_154931_Firefox](https://github.com/jeanbellynck/Cayley-Graph-Generator/assets/44933755/0d4cee99-5721-4d44-9bb1-fe321815ecaf)

**Comment by p4jo** [comment]
Maybe just make them a bit transparent as a hotfix?

**Comment by jeanbellynck** [comment]
This should be fixed by the fact that splines are rendered by default
